homeassistant:
  customize:
    binary_sensor.vacancy:
      friendly_name: Empty House
group:
  vacation_settings:
    name: Vacation
    control: hidden
    entities:
      - input_boolean.vacation_ian
      - input_boolean.vacation_aimee
  network_phones:
    name: Phones
    entities:
      - device_tracker.network_aimees_iphone
      - device_tracker.network_ians_iphone
binary_sensor:
- platform: bayesian
  prior: 0.50
  name: 'vacancy'
  probability_threshold: 0.75
  observations:
  - entity_id: 'device_tracker.network_ians_iphone'
    prob_given_true: 0.5
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'not_home'
  - entity_id: 'device_tracker.network_aimees_iphone'
    prob_given_true: 0.5
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'not_home'
- platform: bayesian
  prior: 0.50
  name: 'occupancy'
  probability_threshold: 0.75
  observations:
  - entity_id: 'device_tracker.network_ians_iphone'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.network_aimees_iphone'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'input_boolean.vacation_ian'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'on'
  - entity_id: 'input_boolean.vacation_aimee'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'on'
input_boolean:
  vacation_ian:
    name: 'Vacation - Ian'
    initial: off
    icon: mdi:beach
  vacation_aimee:
    name: 'Vacation - Aimee'
    initial: off
    icon: mdi:beach
automation:
- id: function_presence_home
  alias: "Function - Presence - Home"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - device_tracker.network_ians_iphone
      - device_tracker.network_aimees_iphone
    to: 'home'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.network_ians_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_aimees_iphone
      state: 'not_home'
  action:
  - service: nest.set_away_mode
    data:
      home_mode: home
      structure:
        - Percivale
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.home
      code: !secret alarm_code
- id: function_presence_away
  alias: "Function - Presence - Away"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - device_tracker.network_ians_iphone
      - device_tracker.network_aimees_iphone
    to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.network_ians_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_aimees_iphone
      state: 'not_home'
  action:
  - service: nest.set_away_mode
    data:
      home_mode: away
      structure:
        - Percivale
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.home
      code: !secret alarm_code
- id: test_vacancy
  alias: "Test - Bayesian Vacancy"
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.vacancy
      - binary_sensor.occupancy
  action:
  - service: notify.notify
    data:
      message: >
        Bayesian Sensor Triggered: {{ trigger.entity_id }}        
scene:
- name: Home
  entities:
    alarm_control_panel.home: 'disarmed'
    climate.downstairs: 'home'
- name: Away
  entities:
    alarm_control_panel.home: 'armed_away'
    climate.downstairs: 'eco'
script:
  location_away:
    alias: 'Function - Presence - Away'
    sequence:
    - service: nest.set_away_mode
      data:
        home_mode: away
        structure:
          - Percivale
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
  location_home:
    alias: 'Function - Presence - Home'
    sequence:
    - service: nest.set_away_mode
      data:
        home_mode: home
        structure:
          - Percivale
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
