media_player:
- platform: plex
  entity_namespace: plex
  show_all_controls: true
sensor:
- platform: plex
  host: !secret plex_host
  port: !secret plex_port
  name: Plex
  username: !secret plex_username
  password: !secret plex_password
  server: !secret plex_server
  token: !secret plex_token
