ring:
  username: !secret ring_username
  password: !secret ring_password
binary_sensor:
- platform: ring
  entity_namespace: ring
sensor:
- platform: ring
  entity_namespace: ring
  monitored_conditions:
    - last_activity
    - last_ding
    - last_motion
    - volume
camera:
- platform: ring
  entity_namespace: ring
