nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
binary_sensor:
- platform: nest
  entity_namespace: nest
climate:
- platform: nest
  entity_namespace: nest
sensor:
- platform: nest
  entity_namespace: nest
