- platform: hikvisioncam
  host: 192.168.2.91
  name: PorchMotion
  username: !secret hikvision_username
  password: !secret hikvision_password
- platform: hikvisioncam
  host: 192.168.2.92
  name: BackyardMotion
  username: !secret hikvision_username
  password: !secret hikvision_password
- platform: hikvisioncam
  host: 192.168.2.93
  name: PatioMotion
  username: !secret hikvision_username
  password: !secret hikvision_password
- platform: hikvisioncam
  host: 192.168.2.94
  name: DrivewayMotion
  username: !secret hikvision_username
  password: !secret hikvision_password
- platform: template
  switches:
    downstairs_away:
      friendly_name: Downstairs Away
      value_template: "{{(states.climate.downstairs.attributes|default({})).away_mode|default(''''''''''''''''off'''''''''''''''') == ''''''''''''''''on''''''''''''''''}}"
      turn_on:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'True'
      turn_off:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'False'
    upstairs_away:
      friendly_name: Upstairs Away
      value_template: "{{(states.climate.upstairs.attributes|default({})).away_mode|default(''''''''''''''''off'''''''''''''''') == ''''''''''''''''on''''''''''''''''}}"
      turn_on:
      - service: climate.set_away_mode
        data:
          entity_id: climate.upstairs
          away_mode: 'True'
      turn_off:
      - service: climate.set_away_mode
        data:
          entity_id: climate.upstairs
          away_mode: 'False'
    bedroom_away:
      friendly_name: Master Away
      value_template: "{{(states.climate.bedroom.attributes|default({})).away_mode|default(''''''''''''''''off'''''''''''''''') == ''''''''''''''''on''''''''''''''''}}"
      turn_on:
      - service: climate.set_away_mode
        data:
          entity_id: climate.bedroom
          away_mode: 'True'
      turn_off:
      - service: climate.set_away_mode
        data:
          entity_id: climate.bedroom
          away_mode: 'False'
    security_armed:
      friendly_name: Home Security Arm
      value_template: "{{states(''''''''''''''''alarm_control_panel.abode_alarm'''''''''''''''') != ''''''''''''''''disarmed''''''''''''''''}}"
      turn_on:
      - service: alarm_control_panel.alarm_arm_away
        entity_id:
          - alarm_control_panel.abode_alarm
          - alarm_control_panel.arlohome
      turn_off:
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.abode_alarm
          - alarm_control_panel.arlohome
    sonos_night_sound:
      friendly_name: Sonos Night Sound
      value_template: "{{state_attr(''''''''''''''''media_player.family_room_2'''''''''''''''',''''''''''''''''night_sound'''''''''''''''')}}"
      turn_on:
      - service: media_player.sonos_set_option
        data:
          entity_id: media_player.family_room_2
          night_sound: True
      turn_off:
      - service: media_player.sonos_set_option
        data:
          entity_id: media_player.family_room_2
          night_sound: False
    sonos_speech_enhance:
      friendly_name: Sonos Speech Enhance
      value_template: "{{state_attr(''''''''''''''''media_player.family_room_2'''''''''''''''',''''''''''''''''speech_enhance'''''''''''''''')}}"
      turn_on:
      - service: media_player.sonos_set_option
        data:
          entity_id: media_player.family_room_2
          speech_enhance: True
      turn_off:
      - service: media_player.sonos_set_option
        data:
          entity_id: media_player.family_room_2
          speech_enhance: False
- platform: command_line
  switches:
    pihole:
      command_on: !secret pihole_enable
      command_off: !secret pihole_disable
      command_state: !secret pihole_status
      value_template: "{{ value_json.status == ''''''''''''''''enabled'''''''''''''''' }}"
      friendly_name: PiHole
