- platform: workday
  name: workday
  country: US
- platform: workday
  name: worknight
  country: US
  days_offset: 1
- platform: iss
  name: 'iss'
  friendly_name: 'International Space Station'
  show_on_map: false
