homeassistant:
  name: !secret hass_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret timezone
  customize: !include customize.yaml
  packages: !include_dir_named packages
frontend: 
ios: 
config: 
http:
  ssl_certificate: !secret http_certificate
  ssl_key: !secret http_key
  trusted_networks: !secret trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 5
updater:
  include_used_components: true
discovery: 
recorder:
  db_url: !secret mysql_uri
  purge_keep_days: 7
  purge_interval: 1
logger:
  default: warn
conversation: 
history: 
logbook: 
map: 
sun: 
tts:
- platform: google
cloud: 
panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: !secret node-red_url
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
weblink:
  entities:
  - name: Home Assistant Webpage
    url: https://home-assistant.io/
    icon: mdi:home-assistant
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    icon: mdi:forum
  - name: Home Assistant Discord
    url: https://discordapp.com/channels/330944238910963714/330944238910963714
    icon: mdi:discord
  - name: Home Assistant Developer Documentation
    url: https://developers.home-assistant.io/
    icon: mdi:code-braces
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml
camera: !include camera.yaml
weather: !include weather.yaml
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
notify:
- name: Pushover
  platform: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key
ifttt:
  key: !secret ifttt_key
octoprint:
- host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  name: !secret octoprint_name
  number_of_tools: 2
  bed: true
